# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb1438fe5084b1c3ffa65eef7cc450c6e8f189f25570715fbe2eda2f8e29eb18dc3784c946185b366608fd7f445d1f6a7456bce05fff12bb2bc94be041c2059

test:
  secret_key_base: 19ba2a636e4fe49e7392e13081a79ede8cec4c033ae4577680f54b11758f4b33163aaf8b44a471cfacfc43309601a5246f333a0be8f4ae5bb36b92d1654074ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
